export const questions = [
    {
        id: "18N.2.SL.TZ0.1d",
        topics: ["4.3.1", "4.3.2"],
        article: "18N.2.SL.TZ0.1d_article.png",
        question: "Using information from the text/data and your knowledge of economics, evaluate the economic impacts of trade protection in the South African corn market. [8 marks]",
        answer: "18N.2.SL.TZ0.1d_answer.png",
    },
    {
        id: "18N.3.HL.TZ0.2e.ii",
        topics: ["4.3.2"],
        article: "18N.3.HL.TZ0.2_article.png",
        question: "With reference to your answer to question (b)(ii) (Answer in (b)(ii): The cost to the government of San Marcus of providing this subsidy to domestic cotton producers is $600 000), calculate the change in the cost of financing the $8 per kg subsidy to the government of San Marcus following the decision to import cotton from the world market. [2 marks]",
        answer: "18N.3.HL.TZ0.2e.ii_answer.png",
    },
    {
        id: "18N.3.HL.TZ0.2e.iii",
        topics: ["4.3.3"],
        article: "18N.3.HL.TZ0.2_article.png",
        question: "Explain one possible advantage and one possible disadvantage for the San Marcus economy of the decision to join the WTO and slowly liberalize trade [4 marks]",
        answer: "18N.3.HL.TZ0.2e.iii_answer.png",
    },
    {
        id: "19M.2.HL.TZ0.1a.i",
        topics: ["4.3.1"],
        article: "19M.2.HL.TZ0.1_article.png",
        question: "Define the term dumping indicated in bold in the text (paragraph [2]). [2 marks]",
        answer: "19M.2.HL.TZ0.1a.i_answer.png",
    },
    {
        id: "19M.2.SL.TZ0.1d",
        topics: ["4.3.1", "4.3.2"],
        article: "19M.2.HL.TZ0.1_article.png",
        question: "Using information from the text/data and your knowledge of economics, evaluate the effect of the tariff on drywall on different stakeholders. [8 marks]",
        answer: "19M.2.HL.TZ0.1a.i_answer.png",
    },
    {
        id: "20N.2.SL.TZ0.2d",
        topics: ["4.3.1", "4.3.2"],
        article: "20N.2.SL.TZ0.2d_article.png",
        question: "Using information from the text/data and your knowledge of economics, discuss the arguments for and against the trade protection measures imposed by the US on China. [8 marks]",
        answer: "20N.2.SL.TZ0.2d_answer.png",
    },
    {
        id: "21N.2.HL.TZ0.2d",
        topics: ["4.3.3"],
        article: "21N.2.HL.TZ0.2d_article.png",
        question: "Using information from the text/data and your knowledge of economics, discuss the economic effects on Indonesia of establishing a free trade agreement with the EU. [8 marks]",
        answer: "21N.2.HL.TZ0.2d_answer.png",
    },
    {
        id: "21N.2.SL.TZ0.1a.i",
        topics: ["4.3.2"],
        article: "21N.2.SL.TZ0.1a.i_article.png",
        question: "Define the term trade war indicated in bold in the text (paragraph [1]). [2 marks]",
        answer: "21N.2.SL.TZ0.1a.i_answer.png",
    },
]
